### ISSUE TITLE
Not compatible with Php 8.1

### ISSUE THREAD

**Issue by signosis** [rdmpage/mendeley-oapi-php#1]
Will this be updated anymore or is this project dead?

**Comment by rdmpage** [comment]
Hi @signosis, I’ve not worked with Mendeley’s API for ages. Once they were bought by Elsevier I lost interest, see also  [Thoughts on Mendeley and Elsevier](https://iphylo.blogspot.com/2013/01/thoughts-on-mendeley-and-elsevier.html). Sorry I can’t be more helpful.
